AWSTemplateFormatVersion: "2010-09-09"

Description: "Template for AWS CLI conversion of files to upload as lambda zip package to S3"
  
Parameters:
  VpcCidrBlock:
    Type: String
    Description: ""
    Default: "10.0.0.0/16"

  AZPublicSubnetA:
    Type: String
    Description: ""
    Default: "us-east-1a"
  
  PublicSubnetACidr:
    Type: String
    Description: ""
    Default: "10.0.0.0/24"
  
  AZPublicSubnetB:
    Type: String
    Description: ""
    Default: "us-east-1b"
  
  PublicSubnetBCidr:
    Type: String
    Description: ""
    Default: "10.0.1.0/24"

  AZPrivateSubnetA:
    Type: String
    Description: ""
    Default: "us-east-1b"

  PrivateSubnetACidr:
    Type: String
    Description: ""
    Default: "10.0.2.0/24"

Resources:
  FortuneExerciseVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: "default"
      Tags:
        - Key: "project"
          Value: "fortune-exercise"
        - Key: "created_by"
          Value: "adinh"

  VpcRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref FortuneExerciseVpc
      Tags:
        - Key: "project"
          Value: "fortune-exercise"
        - Key: "created_by"
          Value: "adinh"
  
  InternetGateway:
    DependsOn: FortuneExerciseVpc
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: "project"
          Value: "fortune-exercise"
        - Key: "created_by"
          Value: "adinh"

  VpcGatewayAssociation:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref FortuneExerciseVpc

  VpcRoutes:
    DependsOn: VpcGatewayAssociation
    Type: AWS::EC2::Route
    Properties: 
      RouteTableId: !Ref VpcRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

  VpcPublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZPublicSubnetA
      CidrBlock: !Ref PublicSubnetACidr
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "project"
          Value: "fortune-exercise"
        - Key: "created_by"
          Value: "adinh"
      VpcId: !Ref FortuneExerciseVpc

  VpcPublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Ref AZPublicSubnetB
      CidrBlock: !Ref PublicSubnetBCidr
      MapPublicIpOnLaunch: true
      Tags:
        - Key: "project"
          Value: "fortune-exercise"
        - Key: "created_by"
          Value: "adinh"
      VpcId: !Ref FortuneExerciseVpc

  VpcPrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AZPrivateSubnetA
      CidrBlock: !Ref PrivateSubnetACidr
      MapPublicIpOnLaunch: false
      Tags:
        - Key: "project"
          Value: "fortune-exercise"
        - Key: "created_by"
          Value: "adinh"
      VpcId: !Ref FortuneExerciseVpc

Outputs:
  VpcId:
    Description: Information about the value
    Value: !Ref FortuneExerciseVpc

  RouteTableId:
    Description: Information about the value
    Value: !Ref VpcRouteTable

  RoutingId:
    Description: Information about the value
    Value: !Ref VpcRoutes
  
  InternetGatewayId:
    Description: Information about the value
    Value: !Ref InternetGateway
  
  PublicSubnetAId:
    Description: Information about the value
    Value: !Ref VpcPublicSubnetA

  PublicSubnetBId:
    Description: Information about the value
    Value: !Ref VpcPublicSubnetB

  PrivateSubnetAId:
    Description: Information about the value
    Value: !Ref VpcPrivateSubnetA
    
