AWSTemplateFormatVersion: "2010-09-09"

Description: ""

Parameters:
  SecurityGroupName:
    Type: String
    Description: ""
    Default: "fortune-exercise-sg"

  FortuneExerciseVPC:
    Type: String
    Description: ""
    Default: "vpc-id"

  FortuneExerciseLambdaArn:
    Type: String
    Description: ""
    Default: "lambda-function-arn"

  ALBName:
    Type: String
    Description: ""
    Default: "fortune-exercise-alb"
    
  VpcPublicSubnetA:
    Type: String
    Description: ""
    Default: "publicSubnetA-id"

  VpcPublicSubnetB:
    Type: String
    Description: ""
    Default: "publicSubnetB-id"

Resources:
  SecurityGroupALB:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: "security group for fortune-exercise"
      GroupName: !Ref SecurityGroupName
      SecurityGroupIngress: 
        - Description: ""
          FromPort: 80
          IpProtocol: "tcp"
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      SecurityGroupEgress: 
        - Description: ""
          FromPort: 80
          IpProtocol: "tcp"
          ToPort: 80
          CidrIp: "0.0.0.0/0"
      Tags: 
        - Key: "project"
          Value: "fortune-exercise"
        - Key: "created_by"
          Value: "adinh"
      VpcId: !Ref FortuneExerciseVPC

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: !Ref ALBName
      IpAddressType: "ipv4"
      Type: "application"
      Scheme: "internet-facing"
      SecurityGroups:
        - !Ref SecurityGroupALB
      Subnets: 
        - !Ref VpcPublicSubnetA
        - !Ref VpcPublicSubnetB
      Tags: 
        - Key: "project"
          Value: "fortune-exercise"
        - Key: "created_by"
          Value: "adinh"

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: "HTTP"

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: "fortune-exercise-target-group"
      HealthCheckEnabled: false
      TargetType: lambda
      Targets: 
        - Id: !Ref FortuneExerciseLambdaArn
      Tags: 
        - Key: "project"
          Value: "fortune-exercise"
        - Key: "created_by"
          Value: "adinh"
      UnhealthyThresholdCount: 2

Outputs:
  SecurityGroupId:
    Description: Information about the value
    Value: !Ref SecurityGroupALB

  LoadBalancerId:
    Description: Information about the value
    Value: !Ref ApplicationLoadBalancer

  ALBListenerId:
    Description: Information about the value
    Value: !Ref ALBListener

  TargetGroupId:
    Description: Information about the value
    Value: !Ref ALBTargetGroup