AWSTemplateFormatVersion: "2010-09-09"
Description: ""

Parameters:
  FortuneLambdaBucketName:
    Type: String
    Description: ""
    Default: "replace-me"

  FortuneLambdaBucketKey:
    Type: String
    Description: ""
    Default: "replace/me.zip"

  FortuneLambdaLayersBucketName:
    Type: String
    Description: ""
    Default: "replace-me"

  FortuneLambdaLayersBucketKey:
    Type: String
    Description: ""
    Default: "replace/me.zip"
  
  VpcStackS3Url:
    Type: String
    Description: ""
    Default: "https://replace.me"

  LambdaS3Url:
    Type: String
    Description: ""
    Default: "https://replace.me"

  ALBS3Url:
    Type: String
    Description: ""
    Default: "https://replace.me"
      
Resources:
  FortuneVpcStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Ref VpcStackS3Url
      Tags: 
        - Key: "project"
          Value: "fortune-exercise"
        - Key: "created_by"
          Value: "adinh"

  FortuneLambdaStack:
    DependsOn: FortuneVpcStack
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Ref LambdaS3Url
      Parameters: 
        LambdaBucketName: !Ref FortuneLambdaBucketName
        LambdaBucketKey: !Ref FortuneLambdaBucketKey
        LambdaLayersBucketName: !Ref FortuneLambdaLayersBucketName
        LambdaLayersBucketKey: !Ref FortuneLambdaLayersBucketKey
      Tags: 
        - Key: "project"
          Value: "fortune-exercise"
        - Key: "created_by"
          Value: "adinh"

  FortuneALBStack:
    DependsOn: FortuneLambdaStack
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Ref ALBS3Url
      Parameters: 
        FortuneExerciseVPC: 
          Fn::GetAtt:
            - FortuneVpcStack
            - Outputs.VpcId
        FortuneExerciseLambdaArn:
          Fn::GetAtt:
            - FortuneLambdaStack
            - Outputs.LambdaFunctionARN
        VpcPublicSubnetA: 
          Fn::GetAtt:
            - FortuneVpcStack
            - Outputs.PublicSubnetAId
        VpcPublicSubnetB: 
          Fn::GetAtt:
            - FortuneVpcStack
            - Outputs.PublicSubnetBId
      Tags: 
        - Key: "project"
          Value: "fortune-exercise"
        - Key: "created_by"
          Value: "adinh"
  
Outputs:
  FortuneVpcStackValues:
    Description: Information about the value
    Value: !Ref FortuneVpcStack

  FortuneLambdaStackValues:
    Description: Information about the value
    Value: !Ref FortuneLambdaStack

  FortuneALBStackValues:
    Description: Information about the value
    Value: !Ref FortuneALBStack
